import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "蓝铭电子标签管理",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
    <head>
        {/* ✅ 添加这行，引用 print-lock.css */}
        <link
          rel="stylesheet"
          media="print"
          href="/print-lock.css" />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
